### ISSUE TITLE
Design der technischen Doku und der Live-Daten vereinheitlichen

### ISSUE THREAD

**Issue by pintman** [tbs1-bo/luftdaten.tbs1.de#3]
Die Daten auf der [Live-Seite des Feinstaub-Sensors](https://it.tbs1.de/luftdaten) werden in einem anderen Layout dargestellt als die [technische Dokumentation](https://tbs1-bo.github.io/luftdaten.tbs1.de). Hier wäre eine Vereinheitlichung schön. 

Dazu müssten folgenden Dateien aus dem Repo jeweils vereinheitlicht werden:

- docs/README.md
- current_values_render/current_values.tpl.html 

Die technische Doku wird von github aus dem Markdown mit Hilfe von [jekyll](https://jekyllrb.com/) in ein statisches HTML generiert. Die Live-Daten werden mit Hilfe eines Python-Scriptes in eine HTML-Datei mit einem Bootstrap-Template generiert. Dadurch kommt es zu Abweichungen im Layout.

**Comment by pintman** [comment]
[mkdocs](http://www.mkdocs.org/) scheint ein vielversprechender Generator für statische Seiten zu sein. Einfache Bedienung, ein sauberes Standard-Template und leichte Installation über Python.

**Comment by linux-lukas** [comment]
Would it be possible to realise the technical documentation with the help of [Sphinx](https://www.sphinx-doc.org/en/master/)?

**Comment by pintman** [comment]
Möglich ja.

**Comment by linux-lukas** [comment]
Okay, to what extent could I participate in this?

**Comment by pintman** [comment]
Live-Data and background information are currently basically the same. Therefore I would not spend time on this. I'd rather prefer to close this outdated issue. But thanks for trying to help out.
