### ISSUE TITLE
Dead link in README.md

### ISSUE THREAD

**Issue by linux-lukas** [tbs1-bo/luftdaten.tbs1.de#5]
The reference to the Ansible documentation in the README.md at [this link here](https://github.com/tbs1-bo/luftdaten.tbs1.de), specifically, the link in this sentence: *"In the playbook, a host luftsensor_deployis used, which must be specified as an inventory in the corresponding hosts file. "* The call to the page fails, with the error message: *"The version of Ansible documentation you were looking at does not contain this page. "*. 

It is likely that the documentation was changed to the point where the link became a dead link.

**Comment by pintman** [comment]
Danke für den Hinweis. Das Problem lässt sich sicher leicht lösen. Magst du einen PR erstellen?

**Comment by linux-lukas** [comment]
Werde ich heute Abend machen.

________________________________

**Comment by linux-lukas** [comment]
Pull Request (PR) is ready
